export default [
  // Ignore vendor, built output, minified bundles, and source fragments
  {
    ignores: [
      'node_modules/',
      'dist/',
      'demos/js/*.min.js',
      'admin/admin-ui.js',
      'dev/head.js',
      'dev/tail.js',
    ],
  },
  // .mjs tooling files — ESM with top-level await support
  {
    files: ['*.mjs'],
    languageOptions: {
      globals: {
        globalThis: 'readonly',
        process: 'readonly',
        __dirname: 'readonly',
        require: 'writable',
        module: 'writable',
        exports: 'writable',
      },
      ecmaVersion: 2022,
      sourceType: 'module',
    },
    linterOptions: {
      reportUnusedDisableDirectives: true,
    },
    rules: {
      'no-console': 'off',
    },
  },
  // dev/ JS + server.js — browser globals allowed
  {
    files: ['dev/**/*.js', 'server.js', 'npm-test.js'],
    languageOptions: {
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        screen: 'readonly',
        console: 'writable',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        URL: 'readonly',
        crypto: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        MediaStream: 'readonly',
        RTCPeerConnection: 'readonly',
        RTCSessionDescription: 'readonly',
        RTCIceCandidate: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        Blob: 'readonly',
        XMLHttpRequest: 'readonly',
        fetch: 'readonly',
        HTMLVideoElement: 'readonly',
        HTMLElement: 'readonly',
        globalThis: 'readonly',
        process: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        require: 'writable',
        module: 'writable',
        exports: 'writable',
        RTCMultiConnection: 'writable',
        SocketConnection: 'writable',
        FirebaseConnection: 'writable',
        PubNubConnection: 'writable',
        SignalRConnection: 'writable',
        detectRTC: 'readonly',
        RecordRTC: 'readonly',
      },
      ecmaVersion: 2021,
      sourceType: 'script',
    },
    linterOptions: {
      reportUnusedDisableDirectives: true,
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-console': 'off',
      strict: 'off',
      eqeqeq: ['warn', 'always', { null: 'ignore' }],
    },
  },
];
